### ISSUE TITLE
User Entity 추가

### ISSUE THREAD

**Issue by m-dzn** [VIA-E-commerce/VIA-Backend#14]
## Todos
- [ ] 인덱스 추가 : email
- [ ] 컬럼 추가
- [ ] 컬럼 제약 조건 추가
- [ ] 유효성 검증 Decorator 추가
- [ ] 컬럼 Api Docs 추가
